import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import '../models/activity_log_model.dart';

class ActivityLogService extends ChangeNotifier {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Log an activity for a specific student
  Future<void> logActivity({
    required String studentId,
    required String moduleName,
    required String action,
  }) async {
    try {
      if (studentId.isEmpty) return;

      final log = ActivityLogModel(
        id: '', // Will be generated by Firestore
        studentId: studentId,
        moduleName: moduleName,
        action: action,
        timestamp: DateTime.now(),
      );

      await _firestore.collection('activity_logs').add(log.toMap());
    } catch (e) {
      debugPrint('Error logging activity: $e');
    }
  }

  // Get a stream of activity logs for a specific student
  Stream<List<ActivityLogModel>> getLogsForStudent(String studentId) {
    if (studentId.isEmpty) {
      return Stream.value([]);
    }

    return _firestore
        .collection('activity_logs')
        .where('studentId', isEqualTo: studentId)
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ActivityLogModel.fromMap(doc.data(), doc.id))
            .toList());
  }

  // Get a stream of ALL activity logs across the system
  Stream<List<ActivityLogModel>> getAllLogs() {
    return _firestore
        .collection('activity_logs')
        .orderBy('timestamp', descending: true)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ActivityLogModel.fromMap(doc.data(), doc.id))
            .toList());
  }
}
